name: Deploy App to EC2 instance

on:
    push:
      branches:
        - 'feature/**'
      tags:
        - 'v*.*.*'
      paths:
        - 'docker/**'
        - '.env'
        - '.github/workflows/**'
    pull_request:
      branches:
        - master
      paths:
        - 'docker/**'
        - '.env' 
        - '.github/workflows/**'

env:
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

jobs: 
  
  deploy-to-ec2:
    name: Deploy app to EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Write SSH key to file
        run: |
          echo "${{ secrets.EC2_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: Append dummy comment to trigger watcher
        run: echo "# updated at $(date)" >> docker/docker-compose.yml

      - name: SCP files to EC2
        run: |
          scp -i ec2_key.pem -o StrictHostKeyChecking=no docker/docker-compose.yml \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ vars.EC2_PATH_PROJECT }}/docker/docker-compose.yml

          scp -i ec2_key.pem -o StrictHostKeyChecking=no .env \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ vars.EC2_PATH_PROJECT }}/.env
        continue-on-error: true
      - name: Run remote deploy script
        run: |
          ssh -i ec2_key.pem -o StrictHostKeyChecking=no \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
            'bash /home/ubuntu/projects/deploy.sh'  
        continue-on-error: true    
                
         
  notify_failure:
    name: Notify Failure on Telegram
    if: failure()
    runs-on: ubuntu-latest
    needs: [deploy-to-ec2]
    steps:
      - name: Send Telegram Message
        run: |
          MESSAGE="🚨 GitHub Action Job FAILED\nRepo: ${{ github.repository }}\nBranch: ${{ github.ref }}\nCommit: ${{ github.sha }}\nJob: ${{ github.job }}"
          curl -s -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage \
            -d chat_id=$TELEGRAM_CHAT_ID \
            -d text="$MESSAGE"
